version: "3"
services:
  db:
    image: postgres
    restart: on_failure
    environment:
      POSTGRES_USER: 'conjugaciones-user'
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_DB: 'conjugaciones'
    ports:
      - "5432:5432"

  client:
    build: ./client
    restart: on-failure
    volumes:
      - ./client:/app
      - ./static:/app/dist

  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "80:8000"
    volumes:
      - ./backend:/app
      - ./static/:/app/static
    depends_on:
      - db
      - client
