version: "3"
services:
  web:
    restart: on-failure
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'mattmatt'
      POSTGRES_PASSWORD: 'mattmatt'
      POSTGRES_DB: 'conjugaciones'
    ports:
      - "5432:5432"

