version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'conjugaciones-user'
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_DB: 'conjugaciones'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db



